---
- name: "Ensure group {{ user_groups }} exists"
  ansible.builtin.group:
    name: "git"
    state: present

- name: add git user
  user:
    name: git
    shell: /usr/bin/git-shell
    groups: "{{ user_groups }}"
    state: present

- name: creates .ssh directory
  file:
    path: /home/git/.ssh
    state: directory
    owner: git
    group: git
    mode: '0700'

- name: copy authorized_keys
  ansible.builtin.copy:
    src: "/home/pi/.ssh/authorized_keys"
    dest: "/home/git/.ssh/authorized_keys"
    owner: git
    group: git
    mode: '0600'

- name: get gid of git user
  command: id -g git
  register: gid_output

- name: get uid of git user
  command: id -u git
  register: uid_output

- set_fact:
    gid: "{{ gid_output.stdout }}"

- set_fact:
    uid: "{{ uid_output.stdout }}"